/**
 * Downloads all media files from WordPress to local /public/wp-media/
 * Reads media-list.json generated by extract.js
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, resolve } from "path";

const MEDIA_DIR = resolve("../public/wp-media");
const EXTRACTED_DIR = "./extracted";

mkdirSync(MEDIA_DIR, { recursive: true });

async function downloadFile(url, destPath) {
  if (existsSync(destPath)) {
    return { status: "skipped", reason: "already exists" };
  }

  const res = await fetch(url);
  if (!res.ok) {
    return { status: "failed", reason: `${res.status} ${res.statusText}` };
  }

  const buffer = Buffer.from(await res.arrayBuffer());
  writeFileSync(destPath, buffer);
  return { status: "ok", size: buffer.length };
}

async function main() {
  const mediaListPath = join(EXTRACTED_DIR, "media-list.json");

  if (!existsSync(mediaListPath)) {
    console.error("❌ media-list.json not found. Run 'node extract.js' first.");
    process.exit(1);
  }

  const mediaList = JSON.parse(readFileSync(mediaListPath, "utf-8"));
  console.log(`=== Downloading ${mediaList.length} media files ===\n`);

  const results = { ok: 0, skipped: 0, failed: 0 };
  const urlMap = {}; // old URL -> new local path

  for (let i = 0; i < mediaList.length; i++) {
    const item = mediaList[i];
    const filename = item.source_url.split("/").pop();
    const destPath = join(MEDIA_DIR, filename);

    process.stdout.write(`[${i + 1}/${mediaList.length}] ${filename}... `);
    const result = await downloadFile(item.source_url, destPath);
    console.log(result.status === "ok" ? `✓ (${(result.size / 1024).toFixed(1)}KB)` : result.status === "skipped" ? "⏭ skipped" : `✗ ${result.reason}`);

    results[result.status === "ok" ? "ok" : result.status === "skipped" ? "skipped" : "failed"]++;

    // Map old WP URL to new local path
    urlMap[item.source_url] = `/wp-media/${filename}`;

    // Also map common WP URL patterns (with and without index.php)
    const wpBase = "https://chiropractorjaipur.com/wp-content/uploads/";
    const pathPart = item.source_url.replace(wpBase, "");
    const justFilename = pathPart.split("/").pop();

    // Map all size variants if they exist
    const baseName = justFilename.replace(/\.[^.]+$/, "");
    const ext = justFilename.match(/\.[^.]+$/)?.[0] || "";

    // Common WP size suffixes
    const sizeSuffixes = [
      "",
      "-150x150",
      "-300x225",
      "-300x300",
      "-300x187",
      "-300x189",
      "-300x168",
      "-768x576",
      "-768x768",
      "-1024x768",
      "-1024x1024",
      "-1024x640",
      "-1024x644",
      "-1536x960",
      "-1536x1152",
      "-600x450",
      "-600x375",
      "-600x377",
      "-600x600",
      "-600x337",
      "-100x100",
      "-700x535",
    ];

    for (const suffix of sizeSuffixes) {
      const sizedFilename = `${baseName}${suffix}${ext}`;
      const sizedUrl = `${wpBase}${pathPart.replace(justFilename, sizedFilename)}`;
      urlMap[sizedUrl] = `/wp-media/${filename}`; // all sizes point to full-size downloaded file
    }

    // Small delay to be respectful to the server
    await new Promise((r) => setTimeout(r, 200));
  }

  // Save URL mapping
  writeFileSync(join(EXTRACTED_DIR, "url-map.json"), JSON.stringify(urlMap, null, 2));

  console.log(`\n=== Download Complete ===`);
  console.log(`✓ Downloaded: ${results.ok}`);
  console.log(`⏭ Skipped:    ${results.skipped}`);
  console.log(`✗ Failed:     ${results.failed}`);
  console.log(`\nMedia saved to: ${MEDIA_DIR}`);
  console.log(`URL mapping saved to: ${EXTRACTED_DIR}/url-map.json`);
}

main().catch(console.error);
